default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "saviour") %>
  password: <%= ENV.fetch("DB_PASSWORD", "Saviour@2021") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: 5432

development:
  <<: *default
  database: stem_development

test:
  <<: *default
  database: stem_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>